### ISSUE TITLE
Package cannot be installed due to conflicts with another require

### ISSUE THREAD

**Issue by chatisk** [ctf0/laravel-firebase-broadcast-driver#2]
Greetings, i am trying to install it but I keep getting this error , can you shed some light here please? 

```
ctf0/firebase-broadcast-driver v1.2.0 requires illuminate/support >=5.5 <9.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, lik
ely because it conflicts with another require.
```

**Comment by chatisk** [comment]
You need to remove the require illuminate/support declaration

**Comment by ctf0** [comment]
i cant remove the `illuminate/support` otherwise u can install it with any fw which is misleading, i've updated the pkg to work with v9, but if possible can u show the full error msg ?

**Comment by chatisk** [comment]
If you made it compatible with v9 , then the issue can be closed, that was the problem , initially. I just forked the package and used it without the illuminate/support. Can't replicate the issue at all.
